### ISSUE TITLE
Rspec is failing a lot, and your README example doesn't seem to work any longer.

### ISSUE THREAD

**Issue by TurtleShip** [sh19910711/codeforces-api.rb#8]
When I try your example, it shows the below example.
![error_message](https://cloud.githubusercontent.com/assets/3166423/12032414/f8476c7e-adcc-11e5-8a99-c23fc9c6068d.png)

I forked your repo and identified that I am seeing the error because you are making `post` request instead of `get` [here](https://github.com/sh19910711/ruby-codeforces-api-client/blob/master/lib/codeforces/api/user.rb#L15)

But wen I fixed it, I still see a whole lot of rspec test failing for different reasons.

Is this gem in WIP not ready to be used yet? I found this repo through here: http://codeforces.com/blog/entry/16113

I am building a website http://codingyard.com and was hoping to use this gem to have my website integrate with Codeforces. If this gem is not ready to be used yet, just tell me and I will create my own client.

Thanks

**Comment by TurtleShip** [comment]
The commit contains many *yml files. Did you mean to include them?

**Comment by sh19910711** [comment]
Hi @TurtleShip 

Thanks for the report. The issue has been fixed, and I have released new version (0.0.13). Please reopen this issue if you still have same issue.

**Comment by sh19910711** [comment]
> The commit contains many *yml files. Did you mean to include them?

Yeah, I added them to reduce the real API access for testing.

**Comment by TurtleShip** [comment]
Hi @sh19910711 

Thanks for fixing this so quickly! I pulled the latest version.
Rspec passes with flying colors, and the gem works as expected :)

:+1:

**Comment by sh19910711** [comment]
That's great. Thank you :bow:
